### ISSUE TITLE
Tree navigation

### ISSUE THREAD

**Issue by troolee** [andy128k/password-storage#23]
It would be great if the arrow keys will be used to navigate over the tree. The usage as I see: LEFT key must move selection to the parent if the current node is password entry. If the current node is a folder it must close if (if it opened). Next - move to the parent. The RIGHT key must open closed folder node.

**Comment by sampablokuper** [comment]
This is due to an [upstream bug in GTK](https://bugzilla.gnome.org/show_bug.cgi?id=105895).
